# Generated by Django 5.1 on 2024-08-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0003_remove_autos_created_remove_autos_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='valor_a_pagar',
            field=models.FloatField(null=True),
        ),
    ]
