# Generated by Django 5.1 on 2024-08-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0004_autos_valor_a_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='valor_a_pagar',
        ),
    ]
