# Generated by Django 5.1 on 2024-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0005_remove_autos_valor_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_a_pagar',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
