# Generated by Django 5.1 on 2024-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0006_cliente_fecha_ingreso_cliente_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
    ]
