# Generated by Django 5.1 on 2024-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0007_alter_cliente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
